<?php

namespace AppBundle\Repository;

/**
 * CurriculumVRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurriculumVRepository extends \Doctrine\ORM\EntityRepository
{
}
